version: "3"

services:
  flask:
    build:
      context: .
      dockerfile: dockerfile
    image: quirosfelipe/phase1
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
  redis:
    image: redis:4.0.11-alpine
